version: '3.8'

services:
  app:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:password@postgres:7002/dbname?sslmode=disable
      - REDIS_URL=redis://redis:7001

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datingapp
    ports:
      - "7002:5432"
  
  migrations:
    build:
      context: ./db
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: ["sh", "-c", 'sleep 10 && goose up']
    volumes:
      - ./db:/db
    environment:
      - GOOSE_DBSTRING=postgres://postgres:postgres@postgres:5432/datingapp?sslmode=disable
      - GOOSE_DRIVER=postgres
      - GOOSE_MIGRATION_DIR=/db/migrations